package main

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"mime"
	"net"
	"net/url"
	"os"
	"os/signal"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/valyala/fasthttp"
	"github.com/valyala/fasthttp/fasthttpproxy"
	"golang.org/x/net/html"
	"golang.org/x/net/html/charset"
	"golang.org/x/text/encoding"

	"github.com/asciimoo/morty/config"
	"github.com/asciimoo/morty/contenttype"
)

const version = "v0.4.1"

const maxRedirectCount = 5

// maxBodySize caps the compressed upstream response on the wire and
// maxUncompressedBodySize caps it after decompression to stop bombs.
const (
	maxBodySize             = 10 * 1024 * 1024 // 10M
	maxUncompressedBodySize = 64 * 1024 * 1024 // 64M
)

var client = &fasthttp.Client{
	MaxResponseBodySize: maxBodySize,
	ReadBufferSize:      16 * 1024, // 16K
	MaxIdleConnDuration: 90 * time.Second,
}

var cfg = config.DefaultConfig

var allowedContentTypeFilter = contenttype.NewFilterOr([]contenttype.Filter{
	// html
	contenttype.NewFilterEquals("text", "html", ""),
	contenttype.NewFilterEquals("application", "xhtml", "xml"),
	// css
	contenttype.NewFilterEquals("text", "css", ""),
	// images
	contenttype.NewFilterEquals("image", "gif", ""),
	contenttype.NewFilterEquals("image", "png", ""),
	contenttype.NewFilterEquals("image", "jpeg", ""),
	contenttype.NewFilterEquals("image", "pjpeg", ""),
	contenttype.NewFilterEquals("image", "webp", ""),
	contenttype.NewFilterEquals("image", "avif", ""),
	contenttype.NewFilterEquals("image", "svg+xml", ""),
	contenttype.NewFilterEquals("image", "tiff", ""),
	contenttype.NewFilterEquals("image", "vnd.microsoft.icon", ""),
	contenttype.NewFilterEquals("image", "bmp", ""),
	contenttype.NewFilterEquals("image", "x-ms-bmp", ""),
	contenttype.NewFilterEquals("image", "x-icon", ""),
	// fonts
	contenttype.NewFilterEquals("font", "otf", ""),
	contenttype.NewFilterEquals("font", "ttf", ""),
	contenttype.NewFilterEquals("font", "woff", ""),
	contenttype.NewFilterEquals("font", "woff2", ""),
	contenttype.NewFilterEquals("application", "font-otf", ""),
	contenttype.NewFilterEquals("application", "font-ttf", ""),
	contenttype.NewFilterEquals("application", "font-woff", ""),
	contenttype.NewFilterEquals("application", "vnd.ms-fontobject", ""),
	// audio/video
	contenttype.NewFilterEquals("audio", "mpeg", ""),
	contenttype.NewFilterEquals("audio", "ogg", ""),
	contenttype.NewFilterEquals("video", "mp4", ""),
	contenttype.NewFilterEquals("video", "webm", ""),
})

var allowedContentTypeAttachmentFilter = contenttype.NewFilterOr([]contenttype.Filter{
	// texts
	contenttype.NewFilterEquals("text", "csv", ""),
	contenttype.NewFilterEquals("text", "tab-separated-values", ""),
	contenttype.NewFilterEquals("text", "plain", ""),
	// API
	contenttype.NewFilterEquals("application", "json", ""),
	// Documents
	contenttype.NewFilterEquals("application", "x-latex", ""),
	contenttype.NewFilterEquals("application", "pdf", ""),
	contenttype.NewFilterEquals("application", "vnd.oasis.opendocument.text", ""),
	contenttype.NewFilterEquals("application", "vnd.oasis.opendocument.spreadsheet", ""),
	contenttype.NewFilterEquals("application", "vnd.oasis.opendocument.presentation", ""),
	contenttype.NewFilterEquals("application", "vnd.oasis.opendocument.graphics", ""),
	// Compressed archives
	contenttype.NewFilterEquals("application", "zip", ""),
	contenttype.NewFilterEquals("application", "gzip", ""),
	contenttype.NewFilterEquals("application", "x-compressed", ""),
	contenttype.NewFilterEquals("application", "x-gtar", ""),
	contenttype.NewFilterEquals("application", "x-compress", ""),
	// Generic binary
	contenttype.NewFilterEquals("application", "octet-stream", ""),
})

// documentCSP is applied to proxified HTML pages: JavaScript is always
// disabled, other resources are allowed because every reference is
// rewritten to same-origin proxified URLs.
const documentCSP = "default-src 'none'; script-src 'none'; img-src 'self' data:; media-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; form-action 'self'; frame-src 'self'; base-uri 'none'"

// pageCSP is applied to pages generated by morty itself.
const pageCSP = "default-src 'none'; style-src 'unsafe-inline'; form-action 'self'"

// Proxy serves sanitized upstream content.
type Proxy struct {
	Key            []byte
	KeyTTL         int64
	RequestTimeout time.Duration
	FollowRedirect bool
	UserAgent      string
	AllowHosts     []string
	DenyHosts      []string
	RateLimiter    *rateLimiter
	Cache          *responseCache
	Metrics        *metrics
}

// requestConfig builds the sanitizer config for one proxified document.
func (p *Proxy) requestConfig(baseURL *url.URL) *RequestConfig {
	rc := &RequestConfig{Key: p.Key, KeyTTL: p.KeyTTL, BaseURL: baseURL}
	if p.Key != nil {
		rc.signer = newHMACSHA256(p.Key)
	}
	return rc
}

// setSecurityHeaders adds headers applied to every response.
func setSecurityHeaders(ctx *fasthttp.RequestCtx, csp string) {
	ctx.Response.Header.Set("X-Content-Type-Options", "nosniff")
	ctx.Response.Header.Set("Referrer-Policy", "no-referrer")
	ctx.Response.Header.Set("X-Robots-Tag", "noindex, nofollow")
	if csp != "" {
		ctx.Response.Header.Set("Content-Security-Policy", csp)
	}
}

func (p *Proxy) RequestHandler(ctx *fasthttp.RequestCtx) {
	if p.appRequestHandler(ctx) {
		return
	}

	// keyless instances are open proxies: rate limit per client IP
	if p.RateLimiter != nil && !p.RateLimiter.allow(ctx.RemoteIP().String()) {
		if p.Metrics != nil {
			p.Metrics.rateLimit()
		}
		p.serveMainPage(ctx, fasthttp.StatusTooManyRequests, errors.New("rate limit exceeded"))
		return
	}

	requestHash := popRequestParam(ctx, []byte("mortyhash"))
	requestExp := popRequestParam(ctx, []byte("mortyexp"))
	requestURI := popRequestParam(ctx, []byte("mortyurl"))

	if requestURI == nil {
		p.serveMainPage(ctx, fasthttp.StatusOK, nil)
		return
	}

	if p.Key != nil {
		if !verifySignedURI(requestURI, requestHash, requestExp, p.Key, p.KeyTTL) {
			if p.Metrics != nil {
				p.Metrics.deny()
			}
			// HTTP status code 403 : Forbidden
			p.serveMainPage(ctx, fasthttp.StatusForbidden, errors.New(`invalid "mortyhash" parameter`))
			return
		}
	}

	requestURIQuery := ctx.QueryArgs().QueryString()
	if len(requestURIQuery) > 0 {
		// requestURI aliases the args buffer, so a copy is required
		// before appending
		merged := append([]byte(nil), requestURI...)
		if bytes.ContainsRune(merged, '?') {
			merged = append(merged, '&')
		} else {
			merged = append(merged, '?')
		}
		requestURI = append(merged, requestURIQuery...)
	}

	p.ProcessURI(ctx, string(requestURI), 0)
}

func (p *Proxy) ProcessURI(ctx *fasthttp.RequestCtx, requestURIStr string, redirectCount int) {
	parsedURI, err := url.Parse(requestURIStr)

	if err != nil {
		p.deny(ctx, fasthttp.StatusInternalServerError, err)
		return
	}

	if parsedURI.Scheme == "" {
		requestURIStr = "https://" + requestURIStr
		parsedURI, err = url.Parse(requestURIStr)
		if err != nil {
			p.deny(ctx, fasthttp.StatusInternalServerError, err)
			return
		}
	}

	// Serve an intermediate page for protocols other than HTTP(S).
	// Hostname() is used so a port suffix cannot bypass the onion check.
	if (parsedURI.Scheme != "http" && parsedURI.Scheme != "https") || strings.HasSuffix(parsedURI.Hostname(), ".onion") {
		p.serveExitMortyPage(ctx, parsedURI)
		return
	}

	// host allow/deny lists apply to the original URL and every redirect hop
	if !hostAllowed(parsedURI.Hostname(), p.AllowHosts, p.DenyHosts) {
		p.deny(ctx, fasthttp.StatusForbidden, errors.New("forbidden host "+parsedURI.Hostname()))
		return
	}

	cacheKey := ""
	if p.Cache != nil && ctx.IsGet() {
		cacheKey = string(ctx.Method()) + "\x00" + requestURIStr
		if entry := p.Cache.get(cacheKey); entry != nil {
			setSecurityHeaders(ctx, "")
			ctx.SetContentType(entry.contentType)
			if entry.disposition != nil {
				ctx.Response.Header.AddBytesV("Content-Disposition", entry.disposition)
			}
			ctx.Write(entry.body)
			p.recordResponse(ctx, fasthttp.StatusOK)
			return
		}
	}

	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)

	slog.Debug("proxified request", "method", string(ctx.Method()), "url", requestURIStr)

	req.SetRequestURI(requestURIStr)
	if p.UserAgent != "" {
		req.Header.SetUserAgentBytes([]byte(p.UserAgent))
	}
	// request identity encoding so upstream responses are readable;
	// compressed answers are still handled below as a fallback
	req.Header.Set("Accept-Encoding", "identity")

	resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(resp)

	req.Header.SetMethodBytes(ctx.Method())
	if ctx.IsPost() || ctx.IsPut() {
		req.SetBody(ctx.PostBody())
		if contentType := ctx.Request.Header.ContentType(); len(contentType) > 0 {
			req.Header.SetContentTypeBytes(contentType)
		}
	}

	start := time.Now()
	err = client.DoTimeout(req, resp, p.RequestTimeout)
	if p.Metrics != nil {
		p.Metrics.observeUpstream(time.Since(start), err)
	}

	if err != nil {
		if errors.Is(err, fasthttp.ErrTimeout) {
			// HTTP status code 504 : Gateway Time-Out
			p.serveMainPage(ctx, fasthttp.StatusGatewayTimeout, err)
		} else {
			// HTTP status code 500 : Internal Server Error
			p.serveMainPage(ctx, fasthttp.StatusInternalServerError, err)
		}
		return
	}

	if resp.StatusCode() != fasthttp.StatusOK {
		switch resp.StatusCode() {
		case fasthttp.StatusMovedPermanently,
			fasthttp.StatusFound,
			fasthttp.StatusSeeOther,
			fasthttp.StatusTemporaryRedirect,
			fasthttp.StatusPermanentRedirect:
			loc := resp.Header.Peek("Location")
			if loc != nil {
				if p.FollowRedirect && ctx.IsGet() {
					// GET method: Morty follows the redirect
					if redirectCount < maxRedirectCount {
						slog.Debug("follow redirect", "to", string(loc))
						// resolve relative redirect targets against the current URI
						nextURI, resolveErr := parsedURI.Parse(string(loc))
						if resolveErr != nil {
							p.serveMainPage(ctx, fasthttp.StatusInternalServerError, resolveErr)
							return
						}
						p.ProcessURI(ctx, nextURI.String(), redirectCount+1)
					} else {
						p.serveMainPage(ctx, fasthttp.StatusPermanentRedirect, errors.New("too many redirects"))
					}
					return
				}
				// Other HTTP methods: Morty does NOT follow the redirect.
				// The Location is proxified (and re-signed when a key and
				// TTL are configured) for this hop.
				rc := p.requestConfig(parsedURI)
				proxifiedURL, err := rc.ProxifyURI(loc)
				if err == nil {
					ctx.SetStatusCode(resp.StatusCode())
					setSecurityHeaders(ctx, "")
					ctx.Response.Header.Add("Location", proxifiedURL)
					if p.Metrics != nil {
						p.Metrics.observeStatus(resp.StatusCode())
					}
					slog.Debug("redirect", "to", string(loc))
					return
				}
			}
		}
		p.serveMainPage(ctx, resp.StatusCode(), fmt.Errorf("invalid response: %d (%s)", resp.StatusCode(), requestURIStr))
		return
	}

	contentTypeBytes := resp.Header.Peek("Content-Type")

	if contentTypeBytes == nil {
		p.serveMainPage(ctx, fasthttp.StatusServiceUnavailable, errors.New("invalid content type"))
		return
	}

	contentTypeString := string(contentTypeBytes)

	// decode Content-Type header
	contentType, err := contenttype.ParseContentType(contentTypeString)
	if err != nil {
		p.serveMainPage(ctx, fasthttp.StatusServiceUnavailable, errors.New("invalid content type"))
		return
	}

	// content-disposition of the upstream response
	contentDispositionBytes := resp.Header.Peek("Content-Disposition")

	// check content type
	if !allowedContentTypeFilter(contentType) {
		// it is not a usual content type
		if allowedContentTypeAttachmentFilter(contentType) {
			// force attachment for allowed content type
			contentDispositionBytes = contentDispositionForceAttachment(contentDispositionBytes, parsedURI)
		} else {
			p.deny(ctx, fasthttp.StatusForbidden, errors.New("forbidden content type "+parsedURI.String()))
			return
		}
	}

	// HACK : replace */xhtml by text/html
	if contentType.SubType == "xhtml" {
		contentType.TopLevelType = "text"
		contentType.SubType = "html"
		contentType.Suffix = ""
	}

	// decompress upstream body when the server ignored our identity
	// request, with a hard cap on the decompressed size
	upstreamBody, err := resp.BodyUncompressedWithLimit(maxUncompressedBodySize)
	if err != nil {
		p.serveMainPage(ctx, fasthttp.StatusServiceUnavailable, err)
		return
	}

	// conversion to UTF-8
	var responseBody []byte

	if contentType.TopLevelType == "text" {
		e, ename, _ := charset.DetermineEncoding(upstreamBody, contentTypeString)
		if (e != encoding.Nop) && (!strings.EqualFold("utf-8", ename)) {
			responseBody, err = e.NewDecoder().Bytes(upstreamBody)
			if err != nil {
				p.serveMainPage(ctx, fasthttp.StatusServiceUnavailable, err)
				return
			}
		} else {
			responseBody = upstreamBody
		}
		// update the charset or specify it
		contentType.Parameters["charset"] = "UTF-8"
	} else {
		responseBody = upstreamBody
	}

	contentType.FilterParameters(allowedContentTypeParameters)

	// set the content type
	ctx.SetContentType(contentType.String())

	// output according to MIME type
	switch {
	case contentType.SubType == "css" && contentType.Suffix == "":
		setSecurityHeaders(ctx, "")
		sanitizeCSS(p.requestConfig(parsedURI), ctx, responseBody)
		p.recordResponse(ctx, fasthttp.StatusOK)
	case contentType.SubType == "html" && contentType.Suffix == "":
		setSecurityHeaders(ctx, documentCSP)
		rc := p.requestConfig(parsedURI)
		sanitizeHTML(rc, ctx, responseBody)
		if !rc.BodyInjected {
			param := htmlBodyExtParam{rc.BaseURL.String(), false}
			if len(rc.Key) > 0 {
				param.HasMortyKey = true
			}
			if err := htmlBodyExtension.Execute(ctx, param); err != nil {
				slog.Debug("failed to inject body extension", "err", err)
			}
		}
		p.recordResponse(ctx, fasthttp.StatusOK)
	default:
		setSecurityHeaders(ctx, "")
		if contentDispositionBytes != nil {
			ctx.Response.Header.AddBytesV("Content-Disposition", contentDispositionBytes)
		}
		ctx.Write(responseBody)
		p.recordResponse(ctx, fasthttp.StatusOK)
		if cacheKey != "" {
			p.Cache.put(cacheKey, responseBody, contentType.String(), contentDispositionBytes)
		}
	}
}

func (p *Proxy) recordResponse(ctx *fasthttp.RequestCtx, code int) {
	ctx.SetStatusCode(code)
	if p.Metrics != nil {
		p.Metrics.observeStatus(code)
	}
}

func (p *Proxy) deny(ctx *fasthttp.RequestCtx, code int, err error) {
	if p.Metrics != nil {
		p.Metrics.deny()
	}
	p.serveMainPage(ctx, code, err)
}

// force content-disposition to attachment
func contentDispositionForceAttachment(contentDispositionBytes []byte, uri *url.URL) []byte {
	var contentDispositionParams map[string]string

	if contentDispositionBytes != nil {
		var err error
		_, contentDispositionParams, err = mime.ParseMediaType(string(contentDispositionBytes))
		if err != nil {
			contentDispositionParams = make(map[string]string)
		}
	} else {
		contentDispositionParams = make(map[string]string)
	}

	if _, fileNameDefined := contentDispositionParams["filename"]; !fileNameDefined {
		contentDispositionParams["filename"] = sanitizeFilename(filepath.Base(uri.Path))
	}

	return []byte(mime.FormatMediaType("attachment", contentDispositionParams))
}

// sanitizeFilename strips characters that are invalid or dangerous in a
// Content-Disposition filename parameter.
func sanitizeFilename(name string) string {
	name = strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f || strings.ContainsRune(`"/\<>:?|`, r) {
			return -1
		}
		return r
	}, name)
	name = strings.TrimSpace(strings.Trim(name, "."))
	if name == "" || len(name) > 128 {
		return "download"
	}
	return name
}

func (p *Proxy) appRequestHandler(ctx *fasthttp.RequestCtx) bool {
	switch string(ctx.Path()) {
	case "/robots.txt":
		ctx.SetContentType("text/plain")
		ctx.Write([]byte("User-Agent: *\nDisallow: /\n"))
		return true
	case "/favicon.ico":
		ctx.SetContentType("image/png")
		ctx.Write(faviconBytes)
		return true
	case "/healthz":
		setSecurityHeaders(ctx, "")
		ctx.SetContentType("text/plain; charset=utf-8")
		ctx.Write([]byte("ok\n"))
		return true
	case "/metrics":
		if p.Metrics == nil {
			return false
		}
		setSecurityHeaders(ctx, "")
		ctx.SetContentType("text/plain; version=0.0.4; charset=utf-8")
		p.Metrics.writeProm(ctx)
		return true
	}
	return false
}

var faviconBytes []byte

func init() {
	faviconBase64 := "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQEAYAAABPYyMiAAAABmJLR0T///////8JWPfcAAAACXBIWXMAAABIAAAASABGyWs+AAAAF0lEQVRIx2NgGAWjYBSMglEwCkbBSAcACBAAAeaR9cIAAAAASUVORK5CYII"
	faviconBytes, _ = base64.StdEncoding.DecodeString(faviconBase64)
}

func popRequestParam(ctx *fasthttp.RequestCtx, paramName []byte) []byte {
	param := ctx.QueryArgs().PeekBytes(paramName)

	if param == nil {
		param = ctx.PostArgs().PeekBytes(paramName)
		ctx.PostArgs().DelBytes(paramName)
	}
	ctx.QueryArgs().DelBytes(paramName)

	return param
}

func hash(msg string, key []byte) string {
	mac := hmac.New(sha256.New, key)
	mac.Write([]byte(msg))
	return hex.EncodeToString(mac.Sum(nil))
}

// signURL signs msg. When ttl seconds is positive the expiry timestamp is
// folded into the HMAC and returned alongside so it can be carried in the
// mortyexp parameter.
func signURL(msg string, key []byte, ttl int64) (string, string) {
	if ttl > 0 {
		exp := time.Now().Add(time.Duration(ttl) * time.Second).Unix()
		return hash(fmt.Sprintf("%s|%d", msg, exp), key), strconv.FormatInt(exp, 10)
	}
	return hash(msg, key), ""
}

func verifyHMAC(uri, hashMsg, key []byte) bool {
	h := make([]byte, hex.DecodedLen(len(hashMsg)))
	if _, err := hex.Decode(h, hashMsg); err != nil {
		slog.Debug("hmac error", "err", err)
		return false
	}
	mac := hmac.New(sha256.New, key)
	mac.Write(uri)
	return hmac.Equal(h, mac.Sum(nil))
}

// verifySignedURI verifies mortyhash. When ttl is positive a valid
// mortyexp parameter is required and must not be expired, otherwise
// unsigned-in-time links are rejected as well.
func verifySignedURI(uri, hashMsg, expMsg, key []byte, ttl int64) bool {
	if ttl > 0 {
		exp, err := strconv.ParseInt(string(expMsg), 10, 64)
		if err != nil || exp <= 0 || time.Now().Unix() > exp {
			return false
		}
		return verifyHMAC([]byte(fmt.Sprintf("%s|%d", uri, exp)), hashMsg, key)
	}
	return verifyHMAC(uri, hashMsg, key)
}

func (p *Proxy) serveExitMortyPage(ctx *fasthttp.RequestCtx, uri *url.URL) {
	ctx.SetContentType("text/html")
	ctx.SetStatusCode(fasthttp.StatusForbidden)
	setSecurityHeaders(ctx, pageCSP)
	if p.Metrics != nil {
		p.Metrics.observeStatus(fasthttp.StatusForbidden)
	}
	ctx.Write([]byte(mortyHTMLPageStart))
	ctx.Write([]byte("<h2>You are about to exit MortyProxy</h2>"))
	ctx.Write([]byte("<p>Following</p><p><a href=\""))
	ctx.Write([]byte(html.EscapeString(uri.String())))
	ctx.Write([]byte("\" rel=\"noreferrer\">"))
	ctx.Write([]byte(html.EscapeString(uri.String())))
	ctx.Write([]byte("</a></p><p>the content of this URL will be <b>NOT</b> sanitized.</p>"))
	ctx.Write([]byte(mortyHTMLPageEnd))
}

func (p *Proxy) serveMainPage(ctx *fasthttp.RequestCtx, statusCode int, err error) {
	ctx.SetContentType("text/html; charset=UTF-8")
	ctx.SetStatusCode(statusCode)
	setSecurityHeaders(ctx, pageCSP)
	if p.Metrics != nil {
		p.Metrics.observeStatus(statusCode)
	}
	ctx.Write([]byte(mortyHTMLPageStart))
	if err != nil {
		slog.Debug("request failed", "err", err)
		ctx.Write([]byte("<h2>Error: "))
		ctx.Write([]byte(html.EscapeString(err.Error())))
		ctx.Write([]byte("</h2>"))
	}
	if p.Key == nil {
		ctx.Write([]byte(`
		<form method="get">
		Visit url: <input placeholder="https://url.." name="mortyurl" autofocus />
		<input type="submit" value="go" />
		</form>`))
	} else {
		ctx.Write([]byte(`<h3>Warning! This instance does not support direct URL opening.</h3>`))
	}
	ctx.Write([]byte(mortyHTMLPageEnd))
}

func run() error {
	listenAddress := flag.String("listen", cfg.ListenAddress, "Listen address")
	key := flag.String("key", cfg.Key, "HMAC url validation key (base64 encoded) - leave blank to disable validation")
	keyTTL := flag.Uint("keyttl", cfg.KeyTTL, "Signed url lifetime in seconds - 0 disables expiry")
	ipv6 := flag.Bool("ipv6", cfg.IPv6, "Allow IPv6 HTTP requests")
	debug := flag.Bool("debug", cfg.Debug, "Debug mode")
	requestTimeout := flag.Uint("timeout", cfg.RequestTimeout, "Request timeout")
	followRedirect := flag.Bool("followredirect", cfg.FollowRedirect, "Follow HTTP GET redirect")
	allowPrivate := flag.Bool("allowprivate", cfg.AllowPrivate, "Allow requests to private/reserved IP ranges")
	rateLimit := flag.Uint("ratelimit", cfg.RateLimit, "Requests per minute per client IP when no key is set - 0 disables")
	userAgent := flag.String("ua", cfg.UserAgent, "Upstream User-Agent header - empty keeps the upstream default")
	allowHosts := flag.String("allow", cfg.AllowHosts, "Comma separated host suffix allowlist")
	denyHosts := flag.String("deny", cfg.DenyHosts, "Comma separated host suffix denylist")
	metricsEnabled := flag.Bool("metrics", cfg.Metrics, "Enable the /metrics endpoint")
	cacheSize := flag.Uint("cache", cfg.CacheSize, "Response cache size in MB for static content - 0 disables")
	cacheTTL := flag.Uint("cachettl", cfg.CacheTTL, "Response cache entry TTL in seconds")
	proxyenv := flag.Bool("proxyenv", false, "Use a HTTP proxy as set in the environment (HTTP_PROXY, HTTPS_PROXY and NO_PROXY). Overrides -proxy, -socks5, -ipv6.")
	proxy := flag.String("proxy", "", "Use the specified HTTP proxy (ie: '[user:pass@]hostname:port'). Overrides -socks5, -ipv6.")
	socks5 := flag.String("socks5", "", "Use a SOCKS5 proxy (ie: 'hostname:port'). Overrides -ipv6.")
	showVersion := flag.Bool("version", false, "Show version")
	flag.Parse()

	cfg.ListenAddress = *listenAddress
	cfg.Key = *key
	cfg.KeyTTL = *keyTTL
	cfg.IPv6 = *ipv6
	cfg.Debug = *debug
	cfg.RequestTimeout = *requestTimeout
	cfg.FollowRedirect = *followRedirect
	cfg.AllowPrivate = *allowPrivate
	cfg.RateLimit = *rateLimit
	cfg.UserAgent = *userAgent
	cfg.AllowHosts = *allowHosts
	cfg.DenyHosts = *denyHosts
	cfg.Metrics = *metricsEnabled
	cfg.CacheSize = *cacheSize
	cfg.CacheTTL = *cacheTTL

	if *showVersion {
		fmt.Println(version)
		return nil
	}

	logLevel := slog.LevelInfo
	if cfg.Debug {
		logLevel = slog.LevelDebug
	}
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: logLevel})))

	if *proxyenv && os.Getenv("HTTP_PROXY") == "" && os.Getenv("HTTPS_PROXY") == "" {
		return errors.New("-proxyenv is used but no environment variables named 'HTTP_PROXY' and/or 'HTTPS_PROXY' could be found")
	}

	dialTimeout := 15 * time.Second
	switch {
	case *proxyenv:
		client.Dial = fasthttpproxy.FasthttpProxyHTTPDialer()
		slog.Info("using environment defined proxy(ies)")
	case *proxy != "":
		client.Dial = fasthttpproxy.FasthttpHTTPDialer(*proxy)
		slog.Info("using custom HTTP proxy")
	case *socks5 != "":
		client.Dial = fasthttpproxy.FasthttpSocksDialer(*socks5)
		slog.Info("using Socks5 proxy")
	default:
		client.Dial = secureDialer(cfg.IPv6, cfg.AllowPrivate, newDNSCache(time.Minute), dialTimeout)
		if !cfg.AllowPrivate {
			slog.Info("private and reserved upstream addresses are blocked")
		}
		if cfg.IPv6 {
			slog.Info("using dual stack (IPv4/IPv6) direct connections")
		} else {
			slog.Info("using IPv4 only direct connections")
		}
	}

	const maxRequestTimeout = 3600 // 1 hour
	timeout := cfg.RequestTimeout
	if timeout == 0 || timeout > maxRequestTimeout {
		slog.Info("invalid -timeout value, using default", "value", timeout, "default", maxRequestTimeout)
		timeout = maxRequestTimeout
	}

	var cache *responseCache
	if cfg.CacheSize > 0 {
		const maxCacheSize = 65536 // MB
		if cfg.CacheSize > maxCacheSize {
			slog.Info("invalid -cache value, using maximum", "value", cfg.CacheSize, "max", maxCacheSize)
			cfg.CacheSize = maxCacheSize
		}
		// #nosec G115 -- CacheSize is bounded to [1, 65536] above
		cache = newResponseCache(int64(cfg.CacheSize)*1024*1024, time.Duration(cfg.CacheTTL)*time.Second)
	}

	p := &Proxy{
		// #nosec G115 -- timeout is bounded to [1, 3600] above
		RequestTimeout: time.Duration(timeout) * time.Second,
		FollowRedirect: cfg.FollowRedirect,
		UserAgent:      cfg.UserAgent,
		AllowHosts:     splitHostList(cfg.AllowHosts),
		DenyHosts:      splitHostList(cfg.DenyHosts),
		Cache:          cache,
	}

	if cfg.Key != "" {
		var err error
		p.Key, err = base64.StdEncoding.DecodeString(cfg.Key)
		if err != nil {
			return fmt.Errorf("error parsing -key: %w", err)
		}
		// #nosec G115 -- KeyTTL is a uint flag value bounded below
		p.KeyTTL = int64(cfg.KeyTTL)
		if p.KeyTTL > 0 {
			slog.Info("signed urls expire", "ttl_seconds", p.KeyTTL)
		}
	} else if cfg.RateLimit > 0 {
		p.RateLimiter = newRateLimiter(cfg.RateLimit)
		slog.Info("rate limiting enabled for keyless mode", "per_minute", cfg.RateLimit)
	}

	if cfg.Metrics {
		p.Metrics = newMetrics(cache)
		slog.Info("metrics enabled", "path", "/metrics")
	}

	server := &fasthttp.Server{
		Name:               "morty",
		Handler:            p.RequestHandler,
		ReadTimeout:        10 * time.Second,
		WriteTimeout:       p.RequestTimeout + 30*time.Second,
		IdleTimeout:        60 * time.Second,
		MaxRequestBodySize: 4 * 1024 * 1024,
	}

	listener, err := net.Listen("tcp", cfg.ListenAddress)
	if err != nil {
		return fmt.Errorf("cannot listen on %s: %w", cfg.ListenAddress, err)
	}

	slog.Info("listening", "address", cfg.ListenAddress)

	serveErr := make(chan error, 1)
	go func() {
		serveErr <- server.Serve(listener)
	}()

	stopCtx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()

	select {
	case err := <-serveErr:
		return err
	case <-stopCtx.Done():
		slog.Info("shutting down")
		return server.Shutdown()
	}
}

func main() {
	if err := run(); err != nil {
		slog.Error("fatal", "err", err)
		os.Exit(1)
	}
}
